### ISSUE TITLE
Deletion not supported

### ISSUE THREAD

**Issue by svdvliet** [baezortega/muttree#1]
Deletions in alignment are not supported is this correct?

**Comment by baezortega** [comment]
Hi, that is right, only substitutions are supported at the moment.

**Comment by svdvliet** [comment]
Thanks,
One more questions, sometimes I have a non changing amino acid showing up
G206G for example, is this because of changing codons perhaps? Is there a way to fix this?

On 7 Aug 2018, at 17:00, Adrian Baez-Ortega <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, that is right, only substitutions are supported at the moment.

**Comment by baezortega** [comment]
That's normal, synonymous substitutions are also included in the output. I
think you can filter them out afterwards, as there should be a column in
the output table indicating if the change is nonsynonymous. As for the
tree, one of the output trees shows only candidate recurrent mutations,
which do not include synonymous changes (the criterion used to define
candidate recurrent mutations is as two or more independent nonsynonymous
mutations in the same gene).

**Comment by svdvliet** [comment]
Thanks a lot, I overlooked this tree.
On 7 Aug 2018, at 17:19, Adrian Baez-Ortega <notifications@github.com<mailto:notifications@github.com>> wrote:

That's normal, synonymous substitutions are also included in the output. I
think you can filter them out afterwards, as there should be a column in
the output table indicating if the change is nonsynonymous. As for the
tree, one of the output trees shows only candidate recurrent mutations,
which do not include synonymous changes (the criterion used to define
candidate recurrent mutations is as two or more independent nonsynonymous
mutations in the same gene).
